clippy: add missing const on some fn
error: this could be a `const fn`
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn